GET http://localhost:8080/api/v1/list

###
POST http://localhost:8080/api/v1/add
Content-Type: application/json

{
  "sepalLength": 1000,
  "color": "blue",
  "price": 1000,
  "description": "best flower ever"
}